# -*- coding: utf-8 -*-
"""Sentiment_Analysis_on_Social_Media.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HqVGRnbIroPtJk4IpVw3JVxf5De0W3Hd
"""

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

pip install transformers requests beautifulsoup4

import pandas as pd
import numpy as np
import torch
import requests
from bs4 import BeautifulSoup
import re

from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")
model = AutoModelForSequenceClassification.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")

r=requests.get('https://www.yelp.com/biz/dennys-san-francisco-2')
soup = BeautifulSoup(r.text,'html.parser')
regex = re.compile('.*comment*.')
results= soup.find_all('p',{'class':regex})
reviews = [result.text for result in results]

df = pd.DataFrame(np.array(reviews),columns = ['review'])

def Sentiment_Score(review):
  tokens = tokenizer.encode(review, return_tensors='pt')
  result = model(tokens)
  return int(torch.argmax(result.logits))+1

df['sentiment'] = df['review'].apply(lambda x: Sentiment_Score(x[:512]))

df

